<?php

/**
 * @file
 * DrupalAI module.
 */

/**
 * Get the AI prompt template.
 */
function drupalai_get_prompt($type) {
  $path = \Drupal::service('extension.list.module')->getPath('drupalai') . '/files/';

  $filename = '';

  switch ($type) {
    case 'module':
      $filename = 'module-prompt.txt';
      break;

    case 'refactor':
      $filename = 'refactor-prompt.txt';
      break;

    case 'block':
      $filename = 'block-prompt.txt';
      break;

    case 'story':
      $filename = 'story-prompt.txt';
      break;
  }

  return file_get_contents($path . $filename);
}
