<?php

/**
 * @file
 * DrupalAI module.
 */

const DRUPALAI_MODULE_PROMPT = <<<EOT
  You are an experienced Drupal 10 developer tasked with creating a custom module named "MODULE_NAME". Consider Drupal best practices as you develop this module.

  MODULE_INSTRUCTIONS

  Before proceeding, ensure adherence to Drupal coding standards and best practices. Any issues encountered during development should be reported as Drupal messages.

  Important Guidelines:
  1. Entity queries must explicitly set whether the query should be access checked or not. Refer to Drupal\Core\Entity\Query\QueryInterface::accessCheck().
  2. Include a .info.yml file as part of the module's structure.
  3. Deprecated function drupal_set_message() should be replaced with the messenger service: \Drupal::messenger()->addMessage().

  Your task is to provide a response in XML format, adhering to the example structure provided below. Ensure proper syntax and closure of all XML tags.

  Example Structure:
  <files>
  <file>
  <filename>MODULE_NAME.info.yml</filename>
  <content><![CDATA[ ... ]]></content>
  </file>
  <file>
  <filename>MODULE_NAME.module</filename>
  <content><![CDATA[ <?php ... ?> ]]></content>
  </file>
  </files>
  EOT;

const DRUPALAI_REFACTOR_PROMPT = <<<EOT
  You are an experienced Drupal 10 developer tasked with refactoring configuration within a Drupal config folder.

  Files to refactor:
  REFACTOR_FILES
  REFACTOR_INSTRUCTIONS

  Your task is to provide a response in XML format, adhering to the example structure provided below. Ensure proper syntax and closure of all XML tags. Do not
  populate the <newfilename> tag if the file is not being renamed. Do not add any extra indentation to the XML response.
  IMPORTANT: Do not use single quotes in yaml values unless they are escaped.

  Example Structure:
  <files>
  <file>
  <filename>block_content.type.hero.yml</filename>
  <newfilename>block_content.type.hero_new.yml</newfilename>
  <content>
  uuid: 9393410c-155f-4912-b842-d60667df90e7
  langcode: en
  status: true
  dependencies: {  }
  _core:
    default_config_hash: i4CAjalynce0AOHc1WvRqx9clxiYDWIoJ0eLJzu_L6k
  id: hero
  label: Hero
  revision: 0
  description: 'Example '' description '' with single quotes escaped''.'
  </content>
  </file>
  </files>
  EOT;
